import {
  CHANGE_RELATIONSHIPS_NATIVE_PROBLEM_FAMILY_MODULES,
  CHANGE_RELATIONSHIPS_PROBLEM_FAMILY_CAPABILITIES
} from "./change-relationships/index.js";
import {
  DATA_PROBABILITY_NATIVE_PROBLEM_FAMILY_MODULES,
  DATA_PROBABILITY_PROBLEM_FAMILY_CAPABILITIES
} from "./data-probability/index.js";
import {
  GEOMETRY_MEASUREMENT_NATIVE_PROBLEM_FAMILY_MODULES,
  GEOMETRY_MEASUREMENT_PROBLEM_FAMILY_CAPABILITIES
} from "./geometry-measurement/index.js";
import {
  NUMBER_OPERATIONS_NATIVE_PROBLEM_FAMILY_MODULES,
  NUMBER_OPERATIONS_PROBLEM_FAMILY_CAPABILITIES
} from "./number-operations/index.js";
import { PORTFOLIO_SCALE_PROBLEM_FAMILY_MODULES } from "../portfolio-scale.js";

export const DOMAIN_PROBLEM_FAMILY_CAPABILITIES = [
  ...NUMBER_OPERATIONS_PROBLEM_FAMILY_CAPABILITIES,
  ...CHANGE_RELATIONSHIPS_PROBLEM_FAMILY_CAPABILITIES,
  ...GEOMETRY_MEASUREMENT_PROBLEM_FAMILY_CAPABILITIES,
  ...DATA_PROBABILITY_PROBLEM_FAMILY_CAPABILITIES
] as const;

/** 신규 family의 유일한 production 등록 지점은 해당 영역 index다. */
export const DOMAIN_NATIVE_PROBLEM_FAMILY_MODULES = [
  ...NUMBER_OPERATIONS_NATIVE_PROBLEM_FAMILY_MODULES,
  ...CHANGE_RELATIONSHIPS_NATIVE_PROBLEM_FAMILY_MODULES,
  ...GEOMETRY_MEASUREMENT_NATIVE_PROBLEM_FAMILY_MODULES,
  ...DATA_PROBABILITY_NATIVE_PROBLEM_FAMILY_MODULES,
  ...PORTFOLIO_SCALE_PROBLEM_FAMILY_MODULES
] as const;
